name: ci

on:
  workflow_dispatch:
  schedule:
    - cron: '59 23 * * *'
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: daviddriscoll/github-runner-az-dotnet:latest
      - name: Build and push Arc
        id: arc_build
        uses: docker/build-push-action@v5
        with:
          file: ./arc.Dockerfile
          context: .
          push: true
          tags: daviddriscoll/github-arc-runner-az-dotnet:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}